# Generated by Django 5.1 on 2024-08-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_property_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='section',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('OFFICE', 'Office'), ('DUPLEX', 'duplex')], max_length=50),
        ),
    ]
