# Generated by Django 5.1 on 2024-08-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tenant_section_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('HOUSE', 'house'), ('APARTMENT', 'apartment'), ('OFFICE', 'office'), ('DUPLEX', 'duplex')], max_length=50),
        ),
    ]
